In [14]:
using NetCDF: ncread, ncwrite, nccreate
using Statistics: mean
using JSON
using NCDatasets

for separate files:

In [22]:
default_data_folder = "../full_data_set/data_files/BOMEX_LES_DEFAULT"
core_data_folder = "../full_data_set/data_files/BOMEX_LES_CORE"

"../full_data_set/data_files/BOMEX_LES_CORE"

for combined files:

In [23]:
default_file = "../full_data_set/data_files/BOMEX_2/BOMEX_AtmosLESDefault_2020-07-22T10.34.39.nc"
core_file = "../full_data_set/data_files/BOMEX_2/BOMEX_AtmosLESCore_2020-07-22T10.34.39.nc"

"../full_data_set/data_files/BOMEX_2/BOMEX_AtmosLESCore_2020-07-22T10.34.39.nc"

### generate lists of files for the separate case

In [24]:
default_files = sort(readdir(default_data_folder, join=true))
defualt_files = [file for file in default_files if occursin(".nc", file)]
defualt_files = [file for file in default_files if occursin("BOMEX", file)]

361-element Array{String,1}:
 "../full_data_set/data_files/BOMEX_LES_DEFAULT/BOMEX_AtmosLESDefault_0000.nc"
 "../full_data_set/data_files/BOMEX_LES_DEFAULT/BOMEX_AtmosLESDefault_0001.nc"
 "../full_data_set/data_files/BOMEX_LES_DEFAULT/BOMEX_AtmosLESDefault_0002.nc"
 "../full_data_set/data_files/BOMEX_LES_DEFAULT/BOMEX_AtmosLESDefault_0003.nc"
 "../full_data_set/data_files/BOMEX_LES_DEFAULT/BOMEX_AtmosLESDefault_0004.nc"
 "../full_data_set/data_files/BOMEX_LES_DEFAULT/BOMEX_AtmosLESDefault_0005.nc"
 "../full_data_set/data_files/BOMEX_LES_DEFAULT/BOMEX_AtmosLESDefault_0006.nc"
 "../full_data_set/data_files/BOMEX_LES_DEFAULT/BOMEX_AtmosLESDefault_0007.nc"
 "../full_data_set/data_files/BOMEX_LES_DEFAULT/BOMEX_AtmosLESDefault_0008.nc"
 "../full_data_set/data_files/BOMEX_LES_DEFAULT/BOMEX_AtmosLESDefault_0009.nc"
 "../full_data_set/data_files/BOMEX_LES_DEFAULT/BOMEX_AtmosLESDefault_0010.nc"
 "../full_data_set/data_files/BOMEX_LES_DEFAULT/BOMEX_AtmosLESDefault_0011.nc"
 "../full_data_set/data

In [25]:
core_files = sort(readdir(core_data_folder, join=true))
core_files = [file for file in core_files if occursin(".nc", file)]
core_files = [file for file in core_files if occursin("BOMEX", file)]

361-element Array{String,1}:
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0000.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0001.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0002.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0003.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0004.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0005.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0006.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0007.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0008.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0009.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0010.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0011.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0012.nc"
 ⋮
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0349.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0350.nc"
 "../full_data_set/data_files/BOMEX_LES_CORE/BOMEX_0351.nc"
 "../ful

### read in z values

In [26]:
z = ncread(default_files[1], "z")
times = []
for file in default_files
    push!(times, ncread(file, "time")[1])
end

In [27]:
c_z = ncread(core_files[1], "z")
c_times = []
for file in core_files
    push!(c_times, ncread(file, "time")[1])
end

### define desired diagnostic variables

In [35]:
default_grid = Dict("time" => times[1:end], "z" => z)
default_vars = [ 
    "u", 
    "v", 
    "w", 
    "avg_rho", 
    "rho", 
    "qt", 
    "ql",
    "thv",
    "thl",
    "temp",
    "pres",
    "thd",
    "ei",
    "et",
    "ht",
    "hi",
    "w_ht_sgs",
    "qv",
    "w_qt_sgs",
    "var_u",
    "var_v",
    "var_w",
    "w3",
    "tke",
    "var_qt",
    "var_thl",
    "var_ei",
    "cov_w_u",
    "cov_w_v",
    "cov_w_rho",
    "cov_w_qt",
    "cov_w_ql",
    "cov_w_qv",
    "cov_w_thd",
    "cov_w_thv",
    "cov_w_thl",
    "cov_w_ei",
    "cov_qt_thl",
    "cov_qt_ei",
    "cld_frac",
    "cld_top",
    "cld_base",
    "cld_cover"
]

43-element Array{String,1}:
 "u"
 "v"
 "w"
 "avg_rho"
 "rho"
 "qt"
 "ql"
 "thv"
 "thl"
 "temp"
 "pres"
 "thd"
 "ei"
 ⋮
 "cov_w_ql"
 "cov_w_qv"
 "cov_w_thd"
 "cov_w_thv"
 "cov_w_thl"
 "cov_w_ei"
 "cov_qt_thl"
 "cov_qt_ei"
 "cld_frac"
 "cld_top"
 "cld_base"
 "cld_cover"

In [36]:
core_grid = Dict("time" => c_times[1:end], "z" => c_z)
core_vars = [
    "core_frac", 
    "u_core", 
    "v_core", 
    "w_core", 
    "avg_rho_core", 
    "rho_core", 
    "qt_core", 
    "ql_core",
    "thv_core",
    "thl_core",
    "var_u_core",
    "var_v_core",
    "var_w_core",
    "var_qt_core",
    "var_thl_core",
    "var_ei_core",
    "cov_w_rho_core",
    "cov_w_qt_core",
    "cov_w_rho_core",
    "cov_w_thl_core",
    "cov_w_ei_core",
    "cov_qt_thl_core",
    "cov_qt_ei_core"
]

23-element Array{String,1}:
 "core_frac"
 "u_core"
 "v_core"
 "w_core"
 "avg_rho_core"
 "rho_core"
 "qt_core"
 "ql_core"
 "thv_core"
 "thl_core"
 "var_u_core"
 "var_v_core"
 "var_w_core"
 "var_qt_core"
 "var_thl_core"
 "var_ei_core"
 "cov_w_rho_core"
 "cov_w_qt_core"
 "cov_w_rho_core"
 "cov_w_thl_core"
 "cov_w_ei_core"
 "cov_qt_thl_core"
 "cov_qt_ei_core"

### combine data from files into 1 dictionary with entry for each variable

In [49]:
default_data = Dict(var => [] for var in default_vars)
for file in default_files[1:180]
    for var in default_vars
        temp = ncread(file, var)
        temp = reshape(temp, size(temp))
        push!(default_data[var], temp)
    end
end
default_data = Dict(var => vcat(default_data[var]...) for var in default_vars)

Dict{String,Array} with 43 entries:
  "cov_w_qt"   => Float32[0.0 0.0 … 0.0 0.0; -8.66492f-9 -4.51697f-7 … -1.26942…
  "qv"         => Float32[0.0170834 0.0170481 … 0.0030328 0.00300006; 0.0172673…
  "w3"         => Float32[0.0 0.0 … 0.0 0.0; -4.15949f-11 -8.03124f-6 … -5.8143…
  "var_v"      => Float32[0.0 0.0 … 0.0 0.0; 0.0119838 0.00642703 … 3.40348f-6 …
  "cov_w_thv"  => Float32[0.0 0.0 … 0.0 0.0; -2.05306f-5 0.00392057 … 3.12408f-…
  "avg_rho"    => Float32[1.17134 1.16875 … 0.891681 0.889495; 1.1791 1.17637 ……
  "et"         => Float32[59426.6 59420.3 … 43860.7 43933.1; 60381.9 60080.7 … …
  "temp"       => Float32[298.967 298.714 … 283.571 283.393; 299.681 299.483 … …
  "cld_base"   => [394.737, NaN, 552.632, NaN, 552.632, 552.632, 552.632, 500.9…
  "cld_cover"  => Float32[1.0, 0.0, 0.00375, 0.0, 0.0107812, 0.171719, 0.055156…
  "cov_w_v"    => Float32[0.0 0.0 … 0.0 0.0; 2.06543f-6 -2.09243f-5 … -2.11109f…
  "cov_w_u"    => Float32[0.0 0.0 … 0.0 0.0; -2.23249f-5 -8.76904f-6 … -4

In [51]:
core_data = Dict(var => [] for var in core_vars)
for file in core_files[1:180]
    for var in core_vars
        temp = ncread(file, var)
        temp = reshape(temp, size(temp))
        push!(core_data[var], temp)
    end
end
core_data = Dict(var => vcat(core_data[var]...) for var in core_vars)

Dict{String,Array{Float32,2}} with 22 entries:
  "ql_core"         => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "cov_w_thl_core"  => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "core_frac"       => Float32[0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.…
  "cov_w_rho_core"  => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "rho_core"        => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "w_core"          => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "thl_core"        => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "v_core"          => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "var_qt_core"     => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "cov_w_qt_core"   => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "var_v_core"      => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "var_ei_core"     => Float32[NaN NaN … NaN NaN; NaN NaN … Na

### turn combined file into dictionary for writing to json

In [54]:
default_data_2 = Dict(var => [] for var in default_vars)
for var in default_vars
    temp = ncread(default_file, var)
    push!(default_data_2[var],temp)
end
default_data_2 = Dict(var => vcat(default_data_2[var]...) for var in default_vars)

Dict{String,Array{Float32,N} where N} with 43 entries:
  "cov_w_qt"   => Float32[0.0 7.62962f-9 … 9.94986f-9 1.03096f-8; 0.0 1.00054f-…
  "qv"         => Float32[0.0170846 0.0172732 … 0.0173276 0.0173256; 0.0170472 …
  "w3"         => Float32[0.0 2.15619f-12 … 1.26892f-13 1.62949f-12; 0.0 -3.388…
  "var_v"      => Float32[0.0 0.0213259 … 0.206604 0.203405; 0.0 0.0180118 … 0.…
  "cov_w_thv"  => Float32[0.0 -1.22383f-5 … 1.6649f-6 1.30678f-6; 0.0 0.0040028…
  "avg_rho"    => Float32[1.17134 1.17375 … 1.17476 1.17476; 1.16875 1.17124 … …
  "et"         => Float32[59426.8 60042.1 … 60530.9 60528.1; 59424.3 59841.2 … …
  "temp"       => Float32[298.964 299.199 … 299.72 299.721; 298.723 298.943 … 2…
  "cld_base"   => Float32[394.737, 552.632, 552.632, 552.632, 500.948, 473.684,…
  "cld_cover"  => Float32[1.0, 0.0034375, 0.006875, 0.0432812, 0.198437, 0.3212…
  "cov_w_v"    => Float32[0.0 1.33929f-7 … 1.20441f-5 1.31341f-5; 0.0 0.0001385…
  "cov_w_u"    => Float32[0.0 7.10456f-6 … 3.1995f-5 3

In [55]:
core_data_2 = Dict(var => [] for var in core_vars)
for var in core_vars
    temp = ncread(core_file, var)
    push!(core_data_2[var],temp)
end
core_data_2 = Dict(var => vcat(core_data_2[var]...) for var in core_vars)

Dict{String,Array{Float32,2}} with 22 entries:
  "ql_core"         => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "cov_w_thl_core"  => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "core_frac"       => Float32[0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.…
  "cov_w_rho_core"  => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "rho_core"        => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "w_core"          => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "thl_core"        => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "v_core"          => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "var_qt_core"     => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "cov_w_qt_core"   => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "var_v_core"      => Float32[NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN Na…
  "var_ei_core"     => Float32[NaN NaN … NaN NaN; NaN NaN … Na

### write dictionaries to json files

In [52]:
string = JSON.json(default_data)
open("../full_data_set/data_files/BOMEX_DIAGNOSTICS_json/BOMEX_1_DEFAULT.json", "w") do x
    write(x, string)
end

7622219

In [58]:
string = JSON.json(default_data_2)
open("../full_data_set/data_files/BOMEX_DIAGNOSTICS_json/BOMEX_2_DEFAULT.json", "w") do x
    write(x, string)
end

7626797

In [56]:
string = JSON.json(core_data)
open("../full_data_set/data_files/BOMEX_DIAGNOSTICS_json/BOMEX_1_CORE.json", "w") do x
    write(x, string)
end

3076427

In [57]:
string = JSON.json(core_data_2)
open("../full_data_set/data_files/BOMEX_DIAGNOSTICS_json/BOMEX_2_CORE.json", "w") do x
    write(x, string)
end

3140969